// *** USER ***
export const USER_UPDATE = "USER_UPDATE";
export const USER_RESET = "USER_RESET";

// *** SETTINGS ***
export const USER_SETTINGS_UPDATE_LANGUAGE = "USER_SETTINGS_UPDATE_LANGUAGE";
export const USER_SETTINGS_UPDATE_ROLE = "USER_SETTINGS_UPDATE_ROLE";
export const USER_SETTINGS_UPDATE_TOKEN = "USER_SETTINGS_UPDATE_TOKEN";

// *** POSTS ***
export const POSTS_UPDATE_LIST = "POSTS_UPDATE_LIST";
export const TEST = "TEST";

// *** USER & SETTINGS ***
export const LOGOUT_USER = 'LOGOUT_USER';
